djmarketplace/app_cart/urls.py
from django.urls import path

from app_cart.views import *

urlpatterns = [
    path('', CartDetailView.as_view(), name='detail_cart'),
    path('add/<int:pk>/', CartAddItem.as_view(), name='add'),
    path('update/<int:pk>/', CartUpdateItem.as_view(), name='update'),
    path('remove/<int:pk>/', CartRemoveItem.as_view(), name='cart_remove'),
]

djmarketplace/app_shop/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from app_shop.views import *

urlpatterns = [
    path('', MaimPageView.as_view(), name='main'),
    path('shop_list/', ShopListView.as_view(), name='shop_list'),
    path('shop_list/<slug:slug>/', ShopListView.as_view(), name='shop_list_category'),
    path('shop_list/<slug:slug>/detail/', cache_page(60 * 60)(ShopDetailView.as_view()), name='shop_detail'),
    path('discount_list/', DiscountListView.as_view(), name='discount'),
    path('discount_list/<slug:slug>/', DiscountListView.as_view(), name='discount_category'),
    path('top_sale/', TopSaleListView.as_view(), name='top_sale'),
    path('new_item_list/', NewItemListView.as_view(), name='new_item'),
    path('new_item_list/<slug:slug>/', NewItemListView.as_view(), name='new_item_category'),
    path('shop/<slug:shop_slug>/item/<int:pk>/detail/', ItemDetailView.as_view(), name='item_detail'),

]

djmarketplace/app_users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from app_users.views import *


urlpatterns = [
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile_edit/<int:pk>/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/<int:pk>/recharge_balance/', UpdateBalanceView.as_view(), name='recharge_balance'),
    path('accounts/loyalty_program/', cache_page(60*60)(LoyaltyProgram.as_view()), name='loyalty_program')
    # path('accounts/change-password/', PasswordChangeView.as_view(), name='change_password'),
]

djmarketplace/djmarketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app_users.urls', 'app_users'), namespace='app_users')),
    path('cart/', include(('app_cart.urls', 'app_cart'), namespace='app_cart')),
    path('order/', include(('app_order.urls', 'app_order'), namespace='app_order')),
    path('', include(('app_shop.urls', 'app_shop'), namespace='app_shop')),

    path('i18n', include('django.conf.urls.i18n')),
    # path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djmarketplace/app_shop/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Count
from django.utils.translation import gettext_lazy as _
from django.shortcuts import render, redirect, get_object_or_404
from django.core.cache import cache
from django.db.models import Q
from django.views.generic import ListView, CreateView, DetailView, TemplateView


from app_cart.forms import CartAddProductForm
from app_order.forms import OrderCreateForm
from app_order.models import OrderItem
from app_shop.models import Item, ItemCategory, Shop, ShopCategory, RepostList


class MixinPaginator(Paginator):
    def my_paginator(self, queryset, request, paginate_by):
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        paginator = Paginator(queryset, paginate_by)
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            queryset = paginator.page(1)
        except EmptyPage:
            queryset = paginator.page(paginator.num_pages)
        return queryset


class MaimPageView(TemplateView):
    """Представление-класс для отображения главной страницы"""

    template_name = 'app_shop/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['discount_items'] = self.discount_items()
        context['new_items'] = self.new_items()
        context['top_sale_items'] = self.top_sale_items()
        context['shops'] = self.shops()
        return context

    def discount_items(self):
        discount_items = Item.objects.select_related('shop__category', 'category').filter(
            Q(discount__gt=0) & Q(stock__gt=0)).order_by('-discount')[:6]
        cache.get_or_set('discount', discount_items, 60)
        return discount_items

    def new_items(self):
        new_items = Item.objects.select_related('shop__category', 'category').exclude(
            discount__gt=0).filter(
            stock__gt=0).order_by('-created_at')[:6]
        cache.get_or_set('new_items', new_items, 60)

        return new_items

    def top_sale_items(self):
        top_sale_items = RepostList.objects.select_related('item__category', 'item__shop__category').filter(
            item__stock__gt=0).order_by('-quantity')[:6]
        cache.get_or_set('top_sale_items', top_sale_items, 60)

        return top_sale_items

    def shops(self):
        shops = Shop.objects.select_related('category').filter(is_active=True)[:6]
        cache.get_or_set('shops', shops, 60)
        return shops


class ShopListView(ListView, MixinPaginator):
    """Представление-класс для отображения списка магазинов"""

    model = Shop
    paginate_by = 4
    template_name = 'app_shop/shop_list.html'
    context_object_name = 'shops'
    queryset = Shop.objects.select_related('category').filter(is_active=True)
    extra_context = {'categories': ShopCategory.objects.all(), }

    def get(self, request, *args, slug=None):
        categories = ShopCategory.objects.filter(shops__is_active=1).annotate(Count('shops'))
        if slug:
            category = get_object_or_404(ShopCategory, slug=slug)
            shops = Shop.objects.filter(category=category.id)
        else:
            shops = self.queryset
        page_obj = self.my_paginator(shops, self.request, self.paginate_by)
        context = {
            'page_obj': page_obj,
            'shops': shops,
            'categories': categories,
        }
        return render(request, 'app_shop/shop_list.html', context)


class ShopDetailView(DetailView, MixinPaginator):
    """Представление-класс для отображения одного магазина"""

    model = Shop
    context_object_name = 'shop'
    slug_url_kwarg = 'slug'
    template_name = 'app_shop/shop_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        items = Item.objects.select_related('shop__category', 'category').filter(shop_id=self.get_object().id)
        items = self.my_paginator(items, self.request, 3)
        context['page_obj'] = items

        return context


class DiscountListView(ListView, MixinPaginator):
    """Представление-класс для отображения списка товаров со скидкой"""
    model = Item
    paginate_by = 4
    template_name = 'app_shop/discount.html'
    context_object_name = 'discounts'
    queryset = Item.objects.select_related('shop__category', 'category').filter(
        Q(discount__gt=0) & Q(stock__gt=0) & Q(shop__is_active=True)).order_by('-discount')
    discount_cache_key = 'discounts_{}'.format(context_object_name)
    cache.get_or_set(discount_cache_key, queryset, 30 * 60)

    def get(self, request, *args, slug=None):
        """Функция для сортировки товаров по лучшей скидки, меньшей цене"""
        categories = {
            'max': _('discounts'),
            'min': _('best price'),
            'five': _('discount < 5%'),
            'ten': _('discount < 10%'),
            'more_ten': _('discount > 10%')
        }
        discounts = Item.objects.select_related('shop__category', 'category')
        if slug == 'max':
            discounts = discounts.filter(discount__gt=0).order_by('-discount')
            category = _('Best discount items')
        elif slug == 'min':
            discounts = discounts.filter(discount__gt=0).order_by('price')
            category = _('Best price')
        elif slug == 'five':
            discount = discounts.filter(Q(discount__gt=1) & Q(discount__lt=6)).order_by('discount')
            category = _('discount up to 5%')
        elif slug == 'ten':
            discounts = discounts.filter(Q(discount__gt=5) & Q(discount__lt=11)).order_by('discount')
            category = _('discount up to 10%')
        elif slug == 'more_ten':
            discounts = discounts.filter(discount__gt=11).order_by('-discount')
            category = _('discount more over 10%')
        else:
            discounts = discounts.filter(discount__gt=0).order_by('-created_at')
            category = _('all items')
        page_obj = self.my_paginator(discounts, self.request, self.paginate_by)
        context = {'page_obj': page_obj, 'category': category, 'categories': categories}
        return render(self.request, 'app_shop/discount.html', context)


class TopSaleListView(ListView):
    """Представление-класс для отображения топовых товаров"""

    model = RepostList
    paginate_by = 5
    template_name = 'app_shop/top_sale.html'
    context_object_name = 'tops'
    queryset = RepostList.objects.select_related('item__shop__category').filter(item__stock__gt=0).order_by('-quantity')


class NewItemListView(ListView, MixinPaginator):
    """Представление-класс для отображения списка новых товаров"""

    model = Item
    paginate_by = 8
    template_name = 'app_shop/new_item.html'
    context_object_name = 'items'
    items_cache_key = 'items_{}'.format(context_object_name)
    queryset = Item.objects.select_related('shop__category', 'category').filter(
        Q(stock__gt=0, shop__is_active=True)).order_by('-created_at')
    cache.get_or_set(items_cache_key, queryset, 30 * 60)

    def get(self, request, *args, slug=None):
        """Функция для сортировки товаров по категориям"""

        category = None
        categories = ItemCategory.objects.filter(items__stock__gt=0).annotate(Count('items'))
        print(categories)
        if slug:
            category = get_object_or_404(ItemCategory, slug=slug)
            items = Item.objects.filter(category=category.id)
        else:
            items = self.queryset
        page_obj = self.my_paginator(items, self.request, self.paginate_by)
        context = {'page_obj': page_obj, 'category': category, 'categories': categories}
        return render(request, 'app_shop/new_item.html', context)


class ItemDetailView(DetailView, CreateView):
    """Представление-класс для отображения одного товара"""
    model = Item
    context_object_name = 'item'
    template_name = 'app_shop/item_detail.html'
    form_class = CartAddProductForm

    def get_context_data(self, **kwargs):
        kwargs['form'] = CartAddProductForm
        kwargs['item'] = Item.objects.select_related('shop__category', 'category').get(pk=self.get_object().id)

        return kwargs

    def get(self, request, *args, **kwargs):
        """Функция-get для отображения формы."""
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        return redirect('app_shop:item_detail', request)

djmarketplace/app_shop/templates/app_shop/item_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %} {{item.category}}/{{ item.name }} {% endblock title %}

{% block content %}

<div class="container">
    <div class="row d-flex justify-content-center">
        <div style="width:29rem; height:25rem"
             class="col col-4 bg-light shadow rounded m-2 p-3 d-flex justify-content-center align-items-center">

            <img class="card-img-top" style="width:15rem; height:15rem"
                 src="{% if item.image %} {{ item.image.url }}
                    {% else %}{% static 'img/default_item.jpg' %} {% endif %}">
        </div>
        <div style="width:29rem; height:25rem" class="col col-6 bg-light shadow rounded m-2 p-3">
            <div class="row ">

                <div class="col col-12  fs-2 fw-bold ">{{ item.name }}</div>
                <div class="col col-12 fs-5 ">{{item.description|truncatechars:20 }}</div>
                <div class="col col-12 fs-5  ">
                    <a href="{{ item.shop.get_absolute_url }}" class="text-decoration-none text-dark">
                        {{ item.shop }}
                    </a>
                </div>
                <div class="col col-12  mb-3 fs-3 fw-bold d-flex justify-content-end align-items-center">
                    {{ item.get_current_price }} {% trans '$' %}
                </div>
                <!--  ADD TO CARD-->
                {% if item.is_stock %}
                {% if request.user.is_authenticated %}
                <div class="col col-12 mt-2">
                    <form id="add_item" action="." method="post" class="form-control-lg p-3">
                        {% csrf_token %}
                        {{ form.quantity }}
                        <small class="text-muted fs-6 fw-light">{{ item.stock }} {% trans 'available pcs'%}</small>
                        {{ form.update }}
                        <button class="btn btn-success m-1 w-50 fw-bold fs-5" form="add_item"
                                formaction="{% url 'app_cart:add' pk=item.id %}" type="submit">
                            Add to cart
                        </button>
                    </form>
                </div>

                <!--  SERVICE MESSAGE -->
                <div class="col col-12 mt-1">
                    <!--   SUCCESS ADDED MESSAGE  -->
                    {% if message == 'successful added to cart' %}
                    <div class="bg-success rounded text-light fs-6 fw-bold p-2 m-1">
                            {% trans 'successful added to cart' %}

                            <!--  BUTTON "GO TO THE CART" -->
                            <a href="{% url 'app_cart:detail_cart' %}" class="btn btn-warning fw-bold w-100 p-1">
                                {% trans 'go to cart'%}
                            </a>
                            <!--  BUTTON "GO TO THE CART" -->

                    </div>
                     <!--   SUCCESS ADDED MESSAGE  -->

                    <!--   LACK OF ITEM  MESSAGE  -->
                    {% elif message == 'lack of the product'%}
                        <div class="bg-danger rounded text-light fs-4 fw-bold p-2 m-1">
                            {% trans 'lack of the product' %}
                        </div>
                    <!--   LACK OF ITEM  MESSAGE  -->
                    {% endif %}
                </div>
                <!--  SERVICE MESSAGE -->

            </div>
        </div>



        <!--                    ADD TO CARD END-->


        {% else %}
        <div class="col col-6 fs-4  d-flex justify-content-start align-self-end">
            <a class="btn btn-dark" href="{% url 'app_users:login' %}">{% trans 'LOG IN to buy'%}</a>
        </div>
        {% endif %}

        {% else %}
        <div class="col col-12 fs-4  d-flex justify-content-end">
            {% trans 'OUT OF STOCK'%}
        </div>
        {% endif %}
        {% if warning_message %}
        <div class="col col-12  d-flex justify-content-center mt-4 p-2 rounded bg-danger text-light text-center">
            {% if warning_message == 'money' %}
            <h3>{% trans 'not enough money to byu' %}</h3>
            {% elif warning_message == 'pcs of item' %}
            <h3>{% trans 'not enough pcs of item' %}</h3>
            {% elif warning_message == 'incorrect number' %}
            <h3>{% trans 'incorrect number, please enter a number' %}</h3>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>
</div>
</div>
</div>


{% endblock content %}


<!--  <div class="row">-->
<!--                                {% for prod in products %}-->
<!--                                <div class="col col-3">-->
<!--                                    <a class="text-decoration-none text-dark"-->
<!--                                       href="{% url 'app_shop:item_detail' shop_slug=prod.shop.slug pk=prod.pk %}">-->

<!--                                        <div class="col col-12 ">-->
<!--                                            <img class="card-img-top"-->
<!--                                                 src="{% if prod.image %} {{ prod.image.url }}-->
<!--                                                 {% else %}{% static 'img/default_item.jpg' %} {% endif %}"-->
<!--                                                 width="150" height="200" alt="image">-->
<!--                                        </div>-->
<!--                                        <div class="col col-12 d-flex justify-content-start">{{ prod.name }}</div>-->
<!--                                        <div class="col col-12 fw-bold d-flex justify-content-start">-->
<!--                                            {{ prod.get_current_price }} $-->
<!--                                        </div>-->
<!--                                    </a>-->
<!--                                </div>-->
<!--                                {% endfor %}-->
<!--                            </div>-->

djmarketplace/app_shop/templates/app_shop/main.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}
{% block title %}{% trans 'main page' %}{% endblock %}

{% block content %}

<div class="container my-5">
    <div class="row d-flex justify-content-center">
        <!-- DISCOUNT   -->
        <div class="col col-3-sm-12  mb-3">
            <div id="carouselExampleSlidesOnly_1" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <a class="text-decoration-none" href="{% url 'app_shop:discount' %}">
                        <div class="text-light text-center  fs-4 p-2 fw-bolder rounded bg-danger ">
                            {% trans 'SALE' %}
                        </div>
                    </a>
                    {% for item in discount_items|slice:'1' %}
                    <div class="carousel-item active card bg-body p-2 rounded">
                        <a class="text-decoration-none text-dark"
                           href="{% url 'app_shop:item_detail' pk=item.pk shop_slug=item.shop.slug %}">
                            <div class="row ">
                                <div class="col col-12 ">
                                    <img class="card-img-top"
                                         src="{% if item.image %} {{ item.image.url }}
                                             {% else %}{% static 'img/default_item.jpg' %}  {% endif %}"
                                         width="150" height="200" alt="image">
                                </div>
                                <div class="col col-12 d-flex justify-content-start">{{ item.name }}</div>
                                <div class="col col-6 fw-lighter d-flex justify-content-end text-decoration-line-through">
                                    {{ item.price }} {% trans '$' %}
                                </div>
                                <div class="col col-6 d-flex fw-bold fs-6 justify-content-end">
                                    {{ item.get_current_price }} {% trans '$' %}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                    {% for item in discount_items|slice:'2:5' %}
                    <div class="carousel-item  card bg-body p-2 rounded">
                        <a class="text-decoration-none text-dark"
                           href="{% url 'app_shop:item_detail' pk=item.pk shop_slug=item.shop.slug %}">
                            <div class="row">
                                <div class="col col-12 ">
                                    <img class="card-img-top"
                                         src="{% if item.image %} {{ item.image.url }}
                                             {% else %}{% static 'img/default_item.jpg' %}  {% endif %}"
                                         width="150" height="200" alt="image">
                                </div>
                                <div class="col col-12 d-flex justify-content-start">{{ item.name }}</div>
                                <div class="col col-6 fw-lighter d-flex justify-content-start text-decoration-line-through">
                                    {{ item.price }} {% trans '$' %}
                                </div>
                                <div class="col col-6 d-flex fw-bold fs-6 justify-content-end">
                                    {{ item.get_current_price }} {% trans '$' %}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- DISCOUNT -->

        <!--  SHOPS -->
        <div class="col  col-3-sm-12  mb-3">
            <div id="carouselExampleSlidesOnly_4" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <a class="text-decoration-none" href="{% url 'app_shop:shop_list' %}">
                        <div class="text-light text-center bg-dark text-light fs-4 p-2 fw-bolder rounded ">
                            {% trans 'OUR SHOPS' %}
                        </div>
                    </a>
                    {% for shop in shops|slice:'1' %}
                    <div class="carousel-item active bg-body p-2 rounded">
                        <a class="text-decoration-none text-dark"
                           href="{% url 'app_shop:shop_detail' slug=shop.slug %}">
                            <div class="row ">
                                <div class="col col-12 ">
                                    <img class="card-img-top"
                                         src="{% if shop.image %} {{ shop.image.url }}
                                             {% else %}{% static 'img/default_shop.jpg' %}  {% endif %}"
                                         width="150" height="200" alt="image">
                                </div>
                                <div class="col col-12 d-flex fw-bold justify-content-start">{{ shop.name }}</div>
                                <div class="col col-12 d-flex justify-content-start">
                                    {{ shop.description|truncatechars:10 }}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                    {% for shop in shops|slice:'2:5' %}
                    <div class="carousel-item bg-body p-2 rounded">
                        <a class="text-decoration-none text-dark"
                           href="{% url 'app_shop:shop_detail' slug=shop.slug %}">
                            <div class="row">
                                <div class="col col-12 ">
                                    <img class="card-img-top"
                                         src="{% if shop.image %} {{ shop.image.url }}
                                             {% else %}{% static 'img/default_ship.jpg' %}  {% endif %}"
                                         width="150" height="200" alt="image">
                                </div>
                                <div class="col col-12 d-flex fs-5 fw-bold justify-content-start">{{ shop.name }}</div>
                                <div class="col col-12 d-flex justify-content-start">
                                    {{ shop.description|truncatechars:10 }}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>

        </div>
        <!-- SHOPS -->

        <!-- NEW ITEMS  -->
        <div class="col  col-3-sm-12  mb-3">
            <div id="carouselExampleSlidesOnly_2" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <a class="text-decoration-none" href="{% url 'app_shop:new_item' %}">
                        <div class="text-light text-center bg-success fs-4 p-2 fw-bolder rounded h-100 ">
                            {% trans 'NEW ITEMS' %}
                        </div>
                    </a>
                    {% for item in new_items|slice:'1' %}
                    <div class="carousel-item active bg-body p-2 rounded">
                        <a class="text-decoration-none text-dark"
                           href="{% url 'app_shop:item_detail' pk=item.pk shop_slug=item.shop.slug %}">
                            <div class="row ">
                                <div class="col col-12 ">
                                    <img class="card-img-top"
                                         src="{% if item.image %} {{ item.image.url }}
                                             {% else %}{% static 'img/default_item.jpg' %}  {% endif %}"
                                         width="150" height="200" alt="image">
                                </div>
                                <div class="col col-12 d-flex justify-content-start">{{ item.name }}</div>
                                <div class="col col-12 fw-bold fs-6 d-flex justify-content-end align-self-end">
                                    {{ item.get_current_price }} {% trans '$' %}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                    {% for item in new_items|slice:'2:5' %}
                    <div class="carousel-item bg-body p-2 rounded">
                        <a class="text-decoration-none text-dark"
                           href="{% url 'app_shop:item_detail' pk=item.pk shop_slug=item.shop.slug %}">
                            <div class="row ">
                                <div class="col col-12 ">
                                    <img class="card-img-top"
                                         src="{% if item.image %} {{ item.image.url }}
                                             {% else %}{% static 'img/default_item.jpg' %}  {% endif %}"
                                         width="150" height="200" alt="image">
                                </div>
                                <div class="col col-12 d-flex justify-content-start">
                                    {{ item.name }}
                                </div>
                                <div class="col col-12 fw-bold fs-6 d-flex justify-content-end align-self-end">
                                    {{ item.get_current_price }} {% trans '$' %}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- NEW ITEMS       -->

        <!-- TOP SALE       -->
        <div class="col  col-3-sm-12  mb-3">
            <div id="carouselExampleSlidesOnly_3" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <a class="text-decoration-none" href="{% url 'app_shop:top_sale' %}">
                        <div class=" text-light text-center fs-4 p-2 fw-bolder bg-warning rounded">
                            {% trans 'TOP SALE' %}
                        </div>
                    </a>
                    {% for top in top_sale_items|slice:'1' %}
                    <div class="carousel-item active bg-body p-2 rounded">
                        <a class="text-decoration-none text-dark"
                           href="{% url 'app_shop:item_detail' shop_slug=top.item.shop.slug pk=top.item.pk %}">
                            <div class="row ">
                                <div class="col col-12 ">
                                    <img class="card-img-top"
                                         src="{% if top.item.image %} {{ top.item.image.url }}
                                             {% else %}{% static 'img/default_item.jpg' %}  {% endif %}"
                                         width="150" height="200" alt="image">
                                </div>
                                <div class="col col-12 d-flex justify-content-start">{{ top.item.name }}</div>
                                <div class="col col-6 fw-bold  fs-6 d-flex justify-content-end align-self-end">
                                    {{ top.item.get_current_price }} {% trans '$' %}
                                </div>
                                <div class="col col-6 d-flex justify-content-start bg-warning rounded ">
                                    {{top.quantity}} {% trans 'bought'%}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                    {% for top in top_sale_items|slice:'2:5' %}
                    <div class="carousel-item bg-body p-2 rounded">
                        <a class="text-decoration-none text-dark"
                           href="{% url 'app_shop:item_detail' shop_slug=top.item.shop.slug pk=top.item.pk %}">
                            <div class="row ">
                                <div class="col col-12 ">
                                    <img class="card-img-top"
                                         src="{% if top.item.image %} {{ top.item.image.url }}
                                             {% else %}{% static 'img/default_item.jpg' %}  {% endif %}"
                                         width="150" height="200" alt="image">
                                </div>
                                <div class="col col-12 d-flex justify-content-start">{{ top.item.name }}</div>
                                <div class="col col-6 fw-bold  fs-6 d-flex justify-content-end align-self-end">
                                    {{ top.item.get_current_price }} {% trans '$' %}
                                </div>
                                <div class="col col-6 d-flex justify-content-start bg-warning rounded ">
                                    {{ top.quantity }} {% trans 'bought'%}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- TOP SALE-->

    </div>
</div>
{% endblock %}