djmarketplace/app_cart/urls.py
from django.urls import path

from app_cart.views import *

urlpatterns = [
    path('', CartDetailView.as_view(), name='detail_cart'),
    path('add/<int:pk>/', CartAddItem.as_view(), name='add'),
    path('update/<int:pk>/', CartUpdateItem.as_view(), name='update'),
    path('remove/<int:pk>/', CartRemoveItem.as_view(), name='cart_remove'),
]

djmarketplace/app_order/urls.py
from django.urls import path

from app_order.views import OrderCreateView, OrderReportDetail, OrderDetail

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('order_statistic/', OrderReportDetail.as_view(), name='order_statistic'),
    path('order_detail/<int:pk>/',  OrderDetail.as_view(), name='order_detail'),
]

djmarketplace/app_shop/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from app_shop.views import *

urlpatterns = [
    path('', MaimPageView.as_view(), name='main'),
    path('shop_list/', ShopListView.as_view(), name='shop_list'),
    path('shop_list/<slug:slug>/', ShopListView.as_view(), name='shop_list_category'),
    path('shop_list/<slug:slug>/detail/', cache_page(60 * 60)(ShopDetailView.as_view()), name='shop_detail'),
    path('discount_list/', DiscountListView.as_view(), name='discount'),
    path('discount_list/<slug:slug>/', DiscountListView.as_view(), name='discount_category'),
    path('top_sale/', TopSaleListView.as_view(), name='top_sale'),
    path('new_item_list/', NewItemListView.as_view(), name='new_item'),
    path('new_item_list/<slug:slug>/', NewItemListView.as_view(), name='new_item_category'),
    path('shop/<slug:shop_slug>/item/<int:pk>/detail/', ItemDetailView.as_view(), name='item_detail'),

]

djmarketplace/djmarketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app_users.urls', 'app_users'), namespace='app_users')),
    path('cart/', include(('app_cart.urls', 'app_cart'), namespace='app_cart')),
    path('order/', include(('app_order.urls', 'app_order'), namespace='app_order')),
    path('', include(('app_shop.urls', 'app_shop'), namespace='app_shop')),

    path('i18n', include('django.conf.urls.i18n')),
    # path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djmarketplace/app_cart/forms.py
from django import forms

QUANTITY = [(i, str(i)) for i in range(1, 16)]


class CartAddProductForm(forms.Form):
    """Форма для выбора кол-ва товара для добавления в корзину """
    quantity = forms.TypedChoiceField(choices=QUANTITY, coerce=int, label='quantity')
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

djmarketplace/app_cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, DetailView, UpdateView

from app_shop.models import Item
from app_cart.cart import Cart
from app_cart.forms import CartAddProductForm


class CartAddItem(View):
    """ Класс-представление для создания корзины с товарами"""
    model = Item
    template_name = 'app_shop/item_detail.html'

    @staticmethod
    def post(request, *args, **kwargs):
        """
         Функция-post для создания корзины.
         Создает объект(запись) ('Cart')
         возвращает на страницу товара.
         в случае успешного добавления товара
         :return: форму, товар и сообщение об успешном добавлении
         в обратном случае
         :return: форму товар и сообщение об ошибки(недостаточно ед. товара)
         :rtype: dict
         """
        cart = Cart(request)
        pk = kwargs['pk']
        item = get_object_or_404(Item, id=pk)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            if item.stock >= quantity:
                cd = form.cleaned_data
                cart.add(product=item,
                         quantity=quantity,
                         update_quantity=cd['update'])
                return render(request, 'app_shop/item_detail.html',
                              {'form': form, 'item': item, 'message': "successful added to cart"})
            return render(request, 'app_shop/item_detail.html',
                          {'form': form, 'item': item, 'message': "lack of the product"})


class CartUpdateItem(UpdateView):
    """ Класс-представление для обновления кол-ва товаров в корзине"""
    model = Item
    template_name = 'app_cart/detail_cart.html'

    def post(self, request, *args, **kwargs):
        """
        Функция-post для обновления кол-ва товара в корзине.
        :return: возвращает на страницу корзины
        :rtype: dict
        """
        cart = Cart(request)
        pk = kwargs['pk']
        item = get_object_or_404(Item, id=pk)
        form = CartAddProductForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            if item.stock >= quantity:
                cd = form.cleaned_data
                cart.update(
                    product=item,
                    quantity=quantity,
                    update_quantity=cd['update']
                )
                return redirect('app_cart:detail_cart')


class CartRemoveItem(TemplateView):
    """ Класс-представление для удаления товара из корзины"""
    model = Item
    template_name = 'app_shop/item_detail.html'

    def get(self, request, *args, **kwargs):
        """
              Функция-get для удаления товара из корзине.
              :return: возвращает на страницу корзины
              :rtype: dict
              """
        pk = kwargs['pk']
        cart = Cart(request)
        product = get_object_or_404(Item, id=pk)
        cart.remove(product)
        return redirect('app_cart:detail_cart')


class CartDetailView(DetailView):
    """ Класс-представление для отображения корзины корзины"""

    model = Item
    template_name = 'app_cart/cart_detail.html'

    def get(self, request, *args, **kwargs):
        """
        Функция-get для отображения корзины.
        возвращает на страницу корзины
        :return: корзину и id пользователя
        :rtype: dict
        """
        cart = Cart(request)
        user = request.user
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                       'update': True})
        context = {'cart': cart, 'user': user}
        return render(request, 'app_cart/cart_detail.html', context)

djmarketplace/app_cart/templates/app_cart/add_cart.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% block title %} add cart {% endblock title %}

{% block content %}
<form action="{% url 'app_cart:detail_cart' product_id=item.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
</form>

{% endblock content %}

djmarketplace/app_cart/templates/app_cart/cart_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %} Your shopping cart {% endblock %}

{% block content %}
<div class="container vh-100">
    <h2 class="d-flex m-1 p-1  fw-bold text-light justify-content-end">Your shopping cart</h2>

    {% if warning_message %}
    <div class="col col-12  d-flex justify-content-center m-2 p-2 rounded bg-danger text-light text-center">
        {% if warning_message == 'money' %}
        <h3>{% trans 'not enough money to byu' %}</h3>
        {% endif %}
        {% endif %}

        {% if cart %}
        <div class="d-flex justify-content-evenly ">
            <table class="bg-light rounded w-100" cellspacing="10">
                <thead>
                <tr class="fs-5 text-center">
                    <th class="p-4">Image</th>
                    <th class="p-4">Product</th>
                    <th class="p-4">Quantity</th>
                    <th class="p-4">4</th>
                    <th class="p-4">Remove</th>
                    <th class="p-4">Unit price</th>
                    <th class="p-4">Price</th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart %}
                <tr class="fs-5 text-center">
                    <td>
                        <img class="m-3 shadow" src="{% if item.product.image %} {{ item.product.image.url }}
            {% else %}{% static 'img/default_item.jpg' %}{% endif %}"
                             width="80" height="80">
                    </td>
                    <td>{{ item.product.name }}</td>
                    <td>{{ item.quantity }}</td>


                    <td>
                        <form id="form_1"class="form-control" action="{% url 'app_cart:update' item.product.id %}" method="post">
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" class="btn btn-sm" value="Обновить">
                            {% csrf_token %}
                        </form>
                    </td>

                    <td><a class="btn btn-danger" href="{% url 'app_cart:cart_remove' item.product.id %}">Remove</a>
                    </td>
                    <td class="num">${{ item.product.get_current_price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="4"></td>
                    <td class="fs-3 fw-bold">Total</td>
                    <td class="fs-3 fw-bold">{{ cart.get_total_price }} $</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="d-flex justify-content-end m-3">
            <a href="{% url 'app_shop:main' %}" class="btn btn-warning btn-lg w-25 mx-2">Continue shopping</a>

            <!-- ADD link to def buy():    -->
            <a href="{% url 'app_order:order_create' %}" class="btn btn-success btn-lg w-25 mx-2">Checkout</a>
            <!---->
        </div>
        {% else %}
        <div class="text-center m-3 text-light fs-2">Oops, not yet anything ...</div>
        {% endif %}
    </div>
</div>
{% endblock %}