djmarketplace/app_cart/urls.py
from django.urls import path

from app_cart.views import *

urlpatterns = [
    path('', CartDetailView.as_view(), name='detail_cart'),
    path('add/<int:pk>/', CartAddItem.as_view(), name='add'),
    path('update/<int:pk>/', CartUpdateItem.as_view(), name='update'),
    path('remove/<int:pk>/', CartRemoveItem.as_view(), name='cart_remove'),
]

djmarketplace/app_order/urls.py
from django.urls import path

from app_order.views import OrderCreateView, OrderReportDetail, OrderDetail

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('order_statistic/', OrderReportDetail.as_view(), name='order_statistic'),
    path('order_detail/<int:pk>/',  OrderDetail.as_view(), name='order_detail'),
]

djmarketplace/app_shop/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from app_shop.views import *

urlpatterns = [
    path('', MaimPageView.as_view(), name='main'),
    path('shop_list/', ShopListView.as_view(), name='shop_list'),
    path('shop_list/<slug:slug>/', ShopListView.as_view(), name='shop_list_category'),
    path('shop_list/<slug:slug>/detail/', cache_page(60 * 60)(ShopDetailView.as_view()), name='shop_detail'),
    path('discount_list/', DiscountListView.as_view(), name='discount'),
    path('discount_list/<slug:slug>/', DiscountListView.as_view(), name='discount_category'),
    path('top_sale/', TopSaleListView.as_view(), name='top_sale'),
    path('new_item_list/', NewItemListView.as_view(), name='new_item'),
    path('new_item_list/<slug:slug>/', NewItemListView.as_view(), name='new_item_category'),
    path('shop/<slug:shop_slug>/item/<int:pk>/detail/', ItemDetailView.as_view(), name='item_detail'),

]

djmarketplace/app_users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from app_users.views import *


urlpatterns = [
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile_edit/<int:pk>/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/<int:pk>/recharge_balance/', UpdateBalanceView.as_view(), name='recharge_balance'),
    path('accounts/loyalty_program/', cache_page(60*60)(LoyaltyProgram.as_view()), name='loyalty_program')
    # path('accounts/change-password/', PasswordChangeView.as_view(), name='change_password'),
]

djmarketplace/djmarketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app_users.urls', 'app_users'), namespace='app_users')),
    path('cart/', include(('app_cart.urls', 'app_cart'), namespace='app_cart')),
    path('order/', include(('app_order.urls', 'app_order'), namespace='app_order')),
    path('', include(('app_shop.urls', 'app_shop'), namespace='app_shop')),

    path('i18n', include('django.conf.urls.i18n')),
    # path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djmarketplace/app_order/models.py
from datetime import datetime
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from app_shop.models import Item
from app_users.models import Profile


class Order(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='profile', null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        db_table = 'app_order'
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        now = datetime.now()
        return '{} - {}'.format(now.strftime("%d-%m-%Y-%H:%M"), self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def get_total_quantity(self):
        return sum(item.get_quantity() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Item, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        db_table = 'app_order_item'
        ordering = ('-order',)
        verbose_name = 'Товар в заказе'
        verbose_name_plural = 'Товары в заказе'

    def __str__(self):
        return f'{self.product}'

    def get_quantity(self):
        return self.quantity

    def get_cost(self):
        price = float(str(self.price))
        quantity = float(str(self.quantity))
        total_cost = price * quantity
        return round(total_cost, 2)


@receiver(post_save, sender=Order)
def create_new_note(instance, **kwargs):
    key = make_template_fragment_key('order_story', [instance.user.profile])
    cache.delete(key)

djmarketplace/app_order/forms.py
from django import forms
from app_order.models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'


class StatDateForm(forms.Form):
    start = forms.DateTimeField()
    finish = forms.DateTimeField()

djmarketplace/app_order/views.py
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.utils.timezone import now
from django.db.models import Sum
from django.shortcuts import render
from django.db import transaction
from django.views import View
from django.views.generic import CreateView, DetailView

from app_shop.models import *
from app_order.models import *
from app_order.forms import *
from app_cart.cart import Cart


class OrderCreateView(LoginRequiredMixin, CreateView):
    """ Класс-представление для создания заказа и оплаты товаров"""
    model = Order
    template_name = 'app_order/new_order.html'
    form_class = OrderCreateForm
    login_url = settings.LOGIN_URL
    permission_required = ('app_order.create_order', 'app_order.view_order')

    def get_context_data(self, **kwargs):
        kwargs['form'] = self.get_form()
        kwargs['cart'] = Cart(self.request)

        return kwargs

    def get(self, request, *args, **kwargs):
        """Функция-get для отображения формы."""
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        """
        Функция-post для покупки товаров из корзины.
        Создает объект(запись) ('Order')
        Создает объект ('OrderItem')
        Создает объект(запись) ('Report List)
        Списывает денежные средства с баланса пользователя('Profile')
        Списывает кол-во единиц купленного товара на складе('Item')
        в случае успешной транзакции
        :return: оформленный заказом
        в обратном случае
        :return: оформленный заказом
        корзину с товарами, форму и сообщение об ошибки(недостаточно средств)
        :rtype: dict
        """

        cart = Cart(request)
        form = self.get_form()
        user = self.request.user.profile
        user_balance = user.get_balance()
        total_cost = cart.get_total_price()
        if total_cost <= user_balance:
            if form.is_valid():
                order = form.save()
                order_list = []
                for item in cart:
                    with transaction.atomic():
                        product = item['product']
                        price = item['price']
                        quantity = item['quantity']
                        order_list.append(OrderItem(
                            order=order,
                            product=product,
                            price=price,
                            quantity=quantity))
                        report, create = RepostList.objects.get_or_create(item=product, quantity=quantity)

                        report.save()
                        product.write_off_item(quantity)
                        product.save()
                        total = float(item['total_price'])
                        user.write_off_money(total)
                        user.save()
                OrderItem.objects.bulk_create(order_list)
                cart.clear()
                return render(request, 'app_order/success_creation.html',
                              {'order': order})
            else:
                context = {'cart': cart, 'form': form}
                return render(request, 'app_order/new_order.html', context)
        else:
            context = {'cart': cart, 'form': form, 'message': 'not enough money to pay, pls, recharge your balance'}
            return render(request, 'app_order/new_order.html', context)


class OrderDetail(DetailView):
    """ Класс-представление для отображения заказа пользователя"""
    model = Order
    template_name = 'app_order/order_detail.html'
    paginate_by = 4
    login_url = settings.LOGIN_URL

    # permission_required = ('app_order.change_order', 'app_order.view_order')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = self.get_object()
        context['items'] = OrderItem.objects.select_related('order').filter(order_id=order.id)
        return context

    # def test_func(self):
    #     """" Проверка на доступ к личной страницы пользователя """
    #
    #     if self.request.user.profile == self.get_object():
    #         return True
    #     return False


class OrderReportDetail(View):
    """
    Класс-представление для создания отчёт по наиболее
    продаваемым товарам за период времени
    """
    model = Order
    template_name = 'app_order/order_statistic.html'
    paginate_by = 4

    def get(self, request):
        """
         Функция для GET-запроса. Возвращает форму для ввода временного периода.

        :return: форма, сообщение о выборе периода(об отсутствии проданных товаров за период времени)
        :rtype:dict
        """
        form = StatDateForm()
        return render(request, 'app_order/order_statistic.html', {'form': form, 'nothing': True})

    def post(self, request, *args, **kwargs):
        """
        Функция для POST-запроса.  Возвращает список проданных  за период времени

        в случае корректных данных:
        :return: форму, список проданных товаров, временное промежуток
        в противном случае:
        :return: форма, сообщение об ошибки(некорректный период)
        :rtype:dict
        """
        form = StatDateForm(request.POST)
        if form.is_valid():
            start = form.cleaned_data.get('start')
            finish = form.cleaned_data.get('finish')
            today = now()
            if start <= finish <= today:
                items = OrderItem.objects.values('product__name', 'product__id', 'product__image'). \
                    filter(order__created__range=(start, finish)). \
                    annotate(Sum('quantity')).order_by('-quantity__sum')
                context = {'others': items, 'form': form, 'date': {'start': start, 'finish': finish}}
                return render(request, 'app_order/order_statistic.html', context)
            else:
                context = {'message': 'error'}
                return render(request, 'app_order/order_statistic.html', context)
        else:
            return render(request, 'app_order/order_statistic.html', {'form': form, 'nothing': 1})

djmarketplace/app_order/templates/app_order/new_order.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %} {% trans 'Checkout' %} {% endblock %}

{% block content %}
<div class="container vh-100">
    <h2 class="d-flex m-1 p-1  fw-bold text-light justify-content-end">{% trans 'Checkout' %}</h2>
    <div class="row">
        <div class="col col-lg-8 bg-light rounded fs-4">
            <h3 class="fs-4 fw-bold">{% trans 'Your order' %}</h3>
            <p class="fs-3 d-flex justify-content-end">{% trans 'Total: $' %} {{ cart.get_total_price }}</p>
            {% for item in cart %}
            <div class="row my-2" >
                <div class="col col-1">
                    <img src="{{ item.product.image.url }}" class="shadow rounded" width="50" height="50">
                </div>
                <div class="col col-6">{{ item.product.name }}</div>
                <div class="col col-1">{{ item.quantity }}</div>
                <div class="col col-2">{{ item.price }}</div>
                <div class="col col-2"><span>{% trans '$' %}{{ item.total_price }}</span></div>
            </div>
            {% endfor %}

        </div>
        <div class="col col-lg-4">
            <form action="." method="post">
                {% csrf_token %}
                <input type="hidden" class="form-control my-2" name="user" value="{{request.user.profile.pk}}">
                <input type="text" class="form-control my-2" name="first_name"
                       value="{{ request.user.first_name }}" aria-label="first_name" readonly>
                <input type="text" class="form-control my-2" name="last_name"
                       value="{{ request.user.last_name }}" aria-label="last_name" readonly>
                <input type="text" class="form-control my-2" name="email"
                       placeholder="{% trans 'email' %}" aria-label="email">
                <input type="hidden" class="form-control my-2" name="paid" value="1">
                <p>
                    <a href="{% url 'app_cart:detail_cart' %}"  class="btn btn-warning m-2 w-20 py-2 ">
                    {% trans 'Back to the cart' %}</a>
                    <input type="submit" class="btn btn-success m-2  py-2 w-50" value="{% trans 'Place order' %}">
                </p>
            </form>
        </div>


        {% if message %}
        <div class="col col-12 bg-danger p-2 text-center fs-3 text-light fw-bold rounded m-1">
            {{message}} <a class="btn btn-warning"
                           href="{% url 'app_users:recharge_balance' pk=request.user.profile.pk %}">
            {% trans 'Recharge balance' %}</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

djmarketplace/app_order/templates/app_order/order_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %} Order detail {{request.user.profile.get_full_name}} {% endblock %}

{% block content %}
<div class="container vh-100">
    <h2 class="d-flex m-1 p-1  fw-bold text-light justify-content-end">Your order</h2>
    <div class="row ">
        <div class="col col-12 m-3 ">
            {% if items %}
            <table class="bg-secondary rounded p-5 w-100 " cellspacing="13">
                <thead>
                <tr class="fs-5  text-center">
                    <th class="p-4">Image</th>
                    <th class="p-4">Item</th>
                    <th class="p-4">Quantity</th>
                    <th class="p-4">Price</th>
                    <th class="p-4">Total</th>
                </tr>
                </thead>
                <tbody>
                {% for order in items %}
                <tr class="fs-5 px-3   text-center">
                    <td class="pb-3"><img src="{{ order.product.image.url }}" width="50"></td>
                    <td class="pb-3">{{ order }}</td>
                    <td class="pb-3">{{ order.quantity }}</td>
                    <td class="pb-3">{{ order.price }}</td>
                    <td class="pb-3">{{ order.get_cost}} {% trans '$' %}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
            <div class="text-center m-3 text-light fs-2">Oops, not yet anything ...</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

djmarketplace/app_order/templates/app_order/order_statistic.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %} {% trans 'Statistic' %} {% endblock %}

{% block content %}
<div class="container vh-100">
    <div class="row">
        <h2 class=" mx-3 p-3  text-light fw-bold d-flex justify-content-end">
            {% if date %}{% trans 'Statistic from' %} {{date.start|date:"d/m/y"}} to {{date.finish|date:"d/m/y"}}
            {% else %}{% trans 'Statistic from' %}{% endif %}
        </h2>
        <!-- DATE FORM       -->
        <div class="col col-lg-sm-12">
            <form method="post" class="form-control bg-secondary p-3 d-flex justify-content-end">
                {% csrf_token %}
                <label for="start"class="fs-4 fw-bold text-light">{% trans 'from' %}</label>
                <input id="start" class="mx-2" type="date" name="start" >
                <label for="start" class="fs-4 fw-bold text-light">{% trans 'to' %}</label>
                <input id="finish" class="mx-2" type="date" name="finish">
                <button class="btn btn-warning  px-5 " type="submit">check</button>
            </form>
        </div>
        <!-- DATE FORM       -->
        <!--  TABLE  + SERVICE MESSAGE -->
        <div class="col col-lg-sm-12">
            <!--  ERROR MESSAGE -->
            {% if message %}
            <div class="bg-danger rounded fs-3 p-1  fw-bold text-center text-light ">
                {% trans 'Incorrect period' %}
            </div>
            {% endif %}
            <!--  ERROR MESSAGE -->

            <!-- TABLE  -->
            {% if others %}
            <table class="bg-secondary text-light rounded w-100" cellspacing="7">
                <thead>
                <tr class="fs-5 ">
                    <th class="p-4">{% trans 'id' %}</th>
                    <th class="p-4">{% trans 'item' %}</th>
                    <th class="p-4">{% trans 'quantity' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for i in others %}
                <tr class="fs-4 p-2 shadow rounded">
                    <td class="p-1">{{ i.product__id}}</td>
                    <td class="p-1">{{ i.product__name }}</td>
                    <td class="p-1">{{ i.quantity__sum }}</td>
                    <td class="p-1">{{ i.order__created}}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% else %}
            <!-- TABLE  -->

            <!--    CHOOSE DATE MESSAGE  -->
            {% if nothing %}
            <div class="text-center m-3 text-light fw-bold fs-3">{% trans 'Choose period' %}</div>
            <!--    CHOOSE DATE MESSAGE  -->

            <!--    EMPTY QUERYSET -->
            {% else %}
            <div class="text-center bg-warning m-3 rounded p-2 fs-5">
                {% trans 'We can not find any info within this period' %}
            </div>
            {% endif %}
            <!--    EMPTY QUERYSET -->
            {% endif %}
        </div>
        <!--  TABLE  + SERVICE MESSAGE -->


    </div>
</div>


{% endblock %}

djmarketplace/app_order/templates/app_order/success_creation.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %}Thank you{% endblock %}

{% block content %}
<div class="container bg-light text-center rounded p-3 my-3 w-70">
    <h1>Successful payment</h1>
    <div class="m-3 fs-5">Thank you, <b>{{request.user.get_full_name }}</b></div>
    <div class="m-3 fs-5">your order number is <strong>{{ order.id }}</strong> has been successfully completed.</div>
    <a class="btn btn-success w-20 p-2 m-2" href="{% url 'app_users:profile' pk=request.user.profile.pk %}">go to my profile</a>
    <a class="btn btn-warning w-20 p-2 m-2" href="{% url 'app_shop:main' %}">Continue shopping</a>
</div>
{% endblock %}