djmarketplace/app_cart/urls.py
from django.urls import path

from app_cart.views import *

urlpatterns = [
    path('', CartDetailView.as_view(), name='detail_cart'),
    path('add/<int:pk>/', CartAddItem.as_view(), name='add'),
    path('update/<int:pk>/', CartUpdateItem.as_view(), name='update'),
    path('remove/<int:pk>/', CartRemoveItem.as_view(), name='cart_remove'),
]

djmarketplace/app_users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from app_users.views import *


urlpatterns = [
    path('accounts/login/', UserLoginView.as_view(), name='login'),
    path('accounts/logout/', UserLogoutView.as_view(), name='logout'),
    path('accounts/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile_edit/<int:pk>/', ProfileUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/<int:pk>/recharge_balance/', UpdateBalanceView.as_view(), name='recharge_balance'),
    path('accounts/loyalty_program/', cache_page(60*60)(LoyaltyProgram.as_view()), name='loyalty_program')
    # path('accounts/change-password/', PasswordChangeView.as_view(), name='change_password'),
]

djmarketplace/djmarketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app_users.urls', 'app_users'), namespace='app_users')),
    path('cart/', include(('app_cart.urls', 'app_cart'), namespace='app_cart')),
    path('order/', include(('app_order.urls', 'app_order'), namespace='app_order')),
    path('', include(('app_shop.urls', 'app_shop'), namespace='app_shop')),

    path('i18n', include('django.conf.urls.i18n')),
    # path('__debug__/', include('debug_toolbar.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djmarketplace/app_users/models.py
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Profile(models.Model):
    """ Модель для создания расширенного профиля пользователя.
        Связь ('O2O') с моделью 'User'.
    """
    LOYALTY_STATUS = [  # уровни программы лояльности
        ('bgn', _('beginner')),
        ('adv', _('advanced')),
        ('ext', _('expert')),
    ]

    SCORE_ADV_STS = 5000  # сумма необходимая для  статуса 'advanced'
    SCORE_EXT_STS = 10000  # сумма необходимая для  статуса 'expert'
    QUOTE = 80  # курс 1 USD = 80 RUB

    default_errors = {
        'required': _('This field is required'),
        'invalid': _('Please enter a valid value')
    }

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile',
        error_messages=default_errors
    )
    verified_id = models.BooleanField(
        default=False,
        verbose_name=_('Verified user')
    )
    avatar = models.ImageField(
        upload_to='profile/%Y/%m/%d',
        default='static/img/default_profile.jpg',
        blank=True,
        null=True,
        verbose_name=_('Avatar')
    )
    balance = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=0,
        verbose_name=_('Balance')
    )
    status = models.CharField(
        max_length=3,
        choices=LOYALTY_STATUS,
        default='bgn',
        verbose_name=_('Loyalty status')
    )

    class Meta:
        db_table = 'app_profile'
        ordering = ['user']
        verbose_name = _('profile')
        verbose_name_plural = _('profiles')

    def __str__(self):
        return f'{self.user}'

    def get_balance(self) -> float:
        """Функция возвращает текущий баланс пользователя"""
        return round(float(self.balance), 2)

    def profile_status(self):
        """ Функция возвращает текущий статус пользователя """

        if self.verified_id:
            return _('Verified Profile')
        return _('Confirmation required')

    def profile_moderated(self) -> bool:
        """ Функция для изменения(верификации)  статуса пользователя """

        self.verified_id = True
        return self.verified_id

    def get_customer(self):
        new_group = Group.objects.get(name='customer')
        user = self.user.groups.add(new_group)
        return user

    def check_loyalty_status(self, total_sum=None) -> str:
        """
        Функция для проверки и обновления статуса
        пользователя в программе лояльности
        """

        if total_sum >= self.SCORE_EXT_STS:
            self.status = 'ext'
        elif total_sum >= self.SCORE_ADV_STS:
            self.status = 'adv'
        else:
            self.status = 'bgn'
        return self.status

    def personal_discount(self, price):
        """
       Функция для подсчета персональной скидки
       пользователя
        """
        if self.status == 'ext':
            price *= 0.95
        elif self.status == 'adv':
            price *= 0.97
        else:
            price *= 1

        return price

    def write_off_money(self, money: float) -> float:
        """
        Функция для списания денежных средств
        с баланса пользователя при покупки товара
        """
        curr_balance = float(self.balance)
        curr_balance -= money
        self.balance = round(curr_balance, 2)
        return curr_balance

    def get_absolute_url(self):
        return reverse('app_users:profile', kwargs={'pk': self.pk})


@receiver(post_save, sender=Profile)
def create_update_note(instance, **kwargs):
    """
    Функция для обновления cache в случае изменения данных на странице пользователя
    :param instance:
    :param kwargs:
    :return:
    """
    key = make_template_fragment_key('profile_info', [instance.user.profile])
    cache.delete(key)


@receiver(post_save, sender=Profile)
def create_new_profile(instance, **kwargs):
    """
      Функция для обновления cache в случае изменения данных пользователя в navbar
      :param instance:
      :param kwargs:
      :return:
      """
    key = make_template_fragment_key('profile', [instance.user.profile])
    cache.delete(key)

djmarketplace/app_users/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Sum, Q, F
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, TemplateView, CreateView

from app_shop.models import Item
from app_users.models import *
from app_order.models import Order, OrderItem
from app_users.forms import RegisterUserForm, UpdateBalanceForm, UpdateProfileForm, UpdateUserForm
from app_users.models import Profile, User


class UserLoginView(LoginView):
    template_name = 'accounts/login.html'
    redirect_field_name = '/'  # reverse('app_shop:main')


class UserLogoutView(LogoutView):
    template_name = 'accounts/logout.html'


class RegisterUserView(CreateView):
    model = User
    template_name = 'accounts/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('app_shop:main')

    def form_valid(self, form):
        user = form.save()
        verified_user = Group.objects.get(name='verified')
        user.groups.add(verified_user)
        Profile.objects.create(
            user=user,
            avatar=form.cleaned_data.get('avatar'),
            balance=0,
            status='bgn',
        )
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(self.request,
                            username=username,
                            password=raw_password)
        login(self.request, user)
        return redirect('app_shop:main')


class ProfileDetailView(UserPassesTestMixin, PermissionRequiredMixin, DetailView):
    """ Класс-представление для отображения личного кабинета пользователя"""
    model = Profile
    template_name = 'accounts/profile.html'
    paginate_by = 4
    login_url = settings.LOGIN_URL
    permission_required = 'app_users.change_profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_purchases'] = self.total_purchases()
        context['total_quantity'] = context['total_purchases'].count()
        context['discount_items'] = self.discount_items()
        context['offer'] = self.offers()
        context['total_sum'] = self.total_sum()
        context['orders'] = self.orders()

        return context

    def test_func(self):
        """" Проверка на доступ к личной страницы пользователя """
        if self.request.user.is_authenticated:
            if self.request.user.profile == self.get_object():
                return True
            return False
        return False

    def orders(self):
        """Функция для отображения всех заказов пользователя """
        orders = Order.objects.select_related('user').filter(user_id=self.object.id).order_by('-created')
        return orders

    def total_purchases(self):
        """" Функция для отображения всех покупок пользователя """
        total_purchases = OrderItem.objects.select_related('order__user').filter(
            order__user_id=self.object.id).order_by('-quantity')
        return total_purchases

    def discount_items(self):
        """" Функция для отображения товаров со скидкой """

        discount_list = Item.objects.select_related('shop', 'category').filter(
            Q(discount__gt=0) & Q(stock__gt=0) & Q(shop__is_active=True)).order_by('-discount')[:10]

        discounts_cache_key = 'discount:{}'.format(self.object.user_id)
        current_cache = cache.get(discounts_cache_key, discount_list)
        if current_cache != discount_list:
            cache.set(discounts_cache_key, discount_list, 60)

        return discount_list

    def offers(self):
        """" Функция для отображения специальных предложений """

        purchase_list = self.total_purchases()

        if purchase_list:
            favorite_cat = purchase_list
            favorite_cat = favorite_cat[0].product.category
            offers_list = Item.objects.select_related('shop', 'category').filter(
                Q(category=favorite_cat) &
                Q(stock__gt=0) &
                Q(shop__is_active=True)).order_by('price')[:5]
            current_cache = cache.get('favorites:{}'.format(self.object.user_id), offers_list)
            if current_cache != offers_list:
                favorites_key_cache = 'favorites:{}'.format(self.object.user_id)
                cache.set(favorites_key_cache, offers_list, 60)

            return offers_list

        return None

    def total_sum(self):
        """"
        Функция для подсчета суммы, потраченной пользователем и
        проверки (обновления) его текущего статуса в программе лояльности
        """

        total_sum = OrderItem.objects.select_related('order__user').filter(order__user_id=self.object.id).order_by(
            '-quantity').aggregate(total=Sum(F('price') * F('quantity')))['total']
        current_status = self.object.status
        if total_sum:
            if total_sum < 5000:  # SCORE_EXT_STS = 10000 $
                need_sum_to_update = round(5000 - float(total_sum))
            else:
                if 10000 > total_sum >= 5000:
                    self.object.status = 'adv'
                    need_sum_to_update = round(10000 - float(total_sum))
                else:
                    self.object.status = 'exp'
                    need_sum_to_update = False
                if current_status != self.object.status:
                    self.object.save()

            return {'sum': round(total_sum,2), 'need_sum_to_update': round(need_sum_to_update, 0)}

        return 0


class UpdateBalanceView(PermissionRequiredMixin, UpdateView):
    """ Класс-представление для пополнения баланса пользователя"""
    model = Profile
    form_class = UpdateBalanceForm
    template_name = 'accounts/recharge_balance.html'
    context_object_name = 'profile'
    permission_required = ('app_users.change_profile', 'app_users.view_profile')

    def test_func(self):
        """" Проверка на доступ к личной страницы пользователя """
        if self.request.user.is_authenticated:
            if self.request.user.profile == self.get_object():
                return True
            return False
        return False

    def form_valid(self, form):
        """" Функция для пополнения баланса пользователя """
        user = self.get_object()
        new_sum = form.cleaned_data['balance']
        if new_sum > 0:
            user.balance = F('balance') + new_sum
            user.save()
            return redirect('app_users:profile', user.pk)
        return redirect('app_users:recharge_balance', user.pk)


class LoyaltyProgram(TemplateView):
    """Представление-класс для отображения программы лояльности"""
    model = Profile
    template_name = 'accounts/loyalty_program.html'


class ProfileUpdateView(UserPassesTestMixin, PermissionRequiredMixin, UpdateView):
    """ Класс-представление для обновления информации о пользователи"""
    model = Profile
    second_model = User
    form_class = UpdateProfileForm
    second_form_class = UpdateUserForm
    template_name = 'accounts/profile_edit.html'
    context_object_name = 'profile'
    permission_required = 'app_users.change_profile'
    login_url = settings.LOGIN_URL

    def test_func(self):
        """" Проверка на доступ к личной страницы пользователя """
        if self.request.user.is_authenticated:
            if self.request.user.profile == self.get_object():
                return True
            return False
        return False

    def get_success_url(self):
        return redirect('app_users:profile', pk=self.get_object().user.profile.pk)

    def get_context_data(self, **kwargs):
        """
        Функция для добавления дополнительной формы,
        для обновления экземпляра расширенной модели пользователя ('Profile')
        """
        kwargs['user_form'] = self.second_form_class()
        kwargs['profile_form'] = self.get_form()
        return kwargs

    def get(self, request, *args, **kwargs):
        """ Функция-get для отображения чистой формы для новых данных о пользователе"""
        return self.render_to_response(self.get_context_data())

    def post(self, request, *args, **kwargs):
        """ Функция-post для отправки обновленных данных о пользователе"""
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            return self.get_success_url()
        else:
            context = {'user_form': user_form, 'profile_form': profile_form}
            return render(request, 'accounts/profile_edit.html', context)

djmarketplace/app_users/templates/accounts/chanche_password.html
{% extends 'base.html' %}

{% block title %}Change Password Page{% endblock title %}

{% block content %}
<h2>Change Password</h2>
<div>
    <!-- form starts here -->
    <form id="change-password-form" method="post" action="#">
        {% csrf_token %}
        <div>
            <label>
                <i aria-hidden="true"></i> old password </label>
            <input id="old_password" name="old_password" placeholder="Enter your old password" required=""
                   type="text">
        </div>
        <div>
            <label>
                <i aria-hidden="true"></i> New Password </label>
            <input name="new_password1" type="password" class="form-control"
                   placeholder="Enter your new password " required="" id="new_password1">
        </div>
        <div>
            <label>
                <i aria-hidden="true"></i> New Password Confirmation </label>
            <input name="new_password2" type="password" class="form-control"
                   placeholder="Enter your new password " required="" id="new_password2">
        </div>
        {% if form.errors %}
        {% for field in form %}
        {{field.name}}
        {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
        {% endfor %}
        {% endfor %}
        {% endif %}
        <div class="w3ls-bot">
            <div class="form-end">
                <input type="submit" value="Submit">
            </div>
            <div class="clearfix"></div>
            <br/>

        </div>

    </form>
</div>
{% endblock content %}

djmarketplace/app_users/templates/accounts/login.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {% trans 'Log in to your account' %} {% endblock %}

{% block content %}
<div class="container-fluid  pt-4 mt-5">
   <div class="row justify-content-center">
    <div class="col-4">
        <h3 class="text-light fs-3 fw-bold text-end">{% trans 'Login' %}</h3>
        <form method="post">
            {% csrf_token %}
             <div class="d-grid mb-4">
                 <div class="form-error text-light">{{form.non_field_errors}}</div>
                 <input type="text" class="form-control my-2" name="username" placeholder="имя" aria-label="username">
                 <input type="password" class="form-control my-2" name="password" placeholder="пароль"
                           aria-label="password1">
                <button class="btn btn-primary btn-lg " type="submit">{% trans 'Login' %}</button>
            </div>
        </form>
   </div>
  </div>
</div>
{% endblock  %}

djmarketplace/app_users/templates/accounts/logout.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} {% trans 'Log out of your account' %}{% endblock %}

{% block content %}
<div align="center" style="margin: 150px">
    <h2 class="fw-bold fs-3 text-light">
        {% trans 'You have successfully logged out' %}
        <a class="btn btn-secondary w-50 my-3 p-3" aria-current="page" href="{% url 'app_users:login' %}">
        {% trans 'login' %}
    </a>
    </h2>
</div>
{% endblock  %}

djmarketplace/app_users/templates/accounts/loyalty_program.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load cache %}
{% get_current_language as LANGUAGE_CODE %}

{% block title %}{% trans 'Loyalty program' %} {{ user.get_full_name}}{% endblock %}

{% block content %}
<div class="container">
    <h2 class="d-flex m-1 p-1  fw-bold text-light justify-content-end">{% trans 'Loyalty program' %}</h2>
    <div class="row d-flex justify-content-around">
            <div class="card shadow rounded" style="width: 18rem; height: 20rem;">
                <div class="card-body">
                     <div class="card-title text-uppercase text-center fs-4 fw-bold p-3">LEVEL</div>
                    <ul class="list-unstyled">
                        <li class="p-3  m-2 bg-light rounded text-dark text-center fs-4 fw-bold">SUM TO UPDATE</li>
                        <li class="p-3  m-2 bg-light rounded text-dark text-center fs-4 fw-bold">DISCOUNT</li>
                    </ul>
                </div>
            </div>
            <div class="card bg-primary rounded text-light  shadow" style="width: 16rem; height: 20rem;">
                <div class="card-body">
                    <div class="card-title text-uppercase text-center fs-3 fw-bold p-3">beginner</div>
                    <ul class="list-unstyled">
                        <li class="p-3  m-2 bg-light rounded text-dark text-center fs-4 fw-bold">0 $</li>
                        <li class="p-3  m-2 bg-light rounded text-dark text-center fs-4 fw-bold">0 %</li>
                    </ul>
                </div>
            </div>
             <div class="card bg-success rounded text-light  shadow" style="width: 17rem; height: 20rem;">
                <div class="card-body">
                   <div class="card-title text-uppercase text-center fs-2 fw-bold p-3">advanced</div>
                    <ul class="list-unstyled">
                     <li class="p-3  m-2 bg-light rounded text-dark text-center fs-4 fw-bold">5 000 $</li>
                    <li class="p-3  m-2 bg-light rounded text-dark text-center fs-4 fw-bold">+3 %</li>
                    </ul>
                </div>
            </div>
            <div class="card bg-danger rounded text-light shadow" style="width: 17rem; height: 20rem;">
                <div class="card-body">
                    <div class="card-title text-uppercase text-center fs-2 fw-bold p-3">expert</div>
                    <ul class="list-unstyled">
                        <li class="p-3  m-2 bg-light rounded text-dark text-center fs-4 fw-bold">10 000 $</li>
                        <li class="p-3  m-2 bg-light rounded text-dark text-center fs-4 fw-bold">+5 %</li>
                    </ul>
                </div>
            </div>
    </div>
</div>

{% endblock content %}

djmarketplace/app_users/templates/accounts/profile_edit.html
{% extends "templates/base.html" %}
{% load i18n %}
{% load static %}
{% block title %}  {% trans 'Edit profile' %} {% endblock %}

{% block content %}

<form method="post" action="" enctype="multipart/form-data">

    {% csrf_token %}
    <div class="container vh-100">
        <div class="row mt-5 d-flex justify-content-center">
            <div class="col-2 bg-light rounded-4 p-3 m-2">
                <img class="rounded-circle m-2 p-1 shadow"
                     src="{% if request.user.profile.avatar %}{{ request.user.profile.avatar.url }}
                    {% else %} {% static 'img/default_profile.jpg' %} {% endif %}" width="120" alt="photo">
                <div class="row my-2 ">
                    <div class="col col-lg-12  d-flex justify-content-center">
                        <b class="mx-2">{{ user.first_name}} {{ user.last_name}}</b>
                    </div>
                    <div class="col col-lg-12  d-flex justify-content-center">
                        <b>{{ user.profile.get_status_display }}</b>
                    </div>
                </div>
            </div>

            <div class="col-5 bg-light rounded-4 p-3 m-2">
                <ul>
                    <input type="text" class="form-control my-2" name="first_name"
                           value="{{ request.user.first_name }}" aria-label="first_name">
                    <input type="text" class="form-control my-2" name="last_name"
                           value="{{ request.user.last_name }}" aria-label="last_name">
                    <div class="input-group">
                        <div class="input-group-text">{% trans 'choose avatar' %}</div>
                        <input type="file" class="form-control" name="avatar"
                               value="{{ request.profile.user.avatar }}" aria-label="avatar"></div>
                    <div class="d-grid mt-3">
                        <button class="btn btn-primary btn-blog" type="submit">{% trans 'Save' %}</button>
                    </div>
                </ul>
            </div>
        </div>
    </div>
</form>

{% endblock %}

djmarketplace/app_users/templates/accounts/recharge_balance.html
{% extends "templates/base.html" %}
{% load i18n %}
{% block title %}  {% trans 'Recharge balance' %} {% endblock %}

{% block content %}

<div class="container w-25 vh-100 ">
    <h2 class="d-flex m-1 p-1  fw-bold text-light justify-content-end">{% trans 'Recharge balance' %}</h2>
    <form method="post" action="" enctype="multipart/form-data"> {% csrf_token %}
        <div class="row mt-5 bg-light rounded-5">
            <div class="col col-12  p-3 d-flex   justify-content-center align-items-center">
                <img class="rounded-circle  shadow border border-5
                     {% if user.profile.status == 'ext'%} border-danger
                     {% elif user.profile.status == 'adv' %} border-success
                     {% else %} border-primary
                     {% endif %}"
                     src="{% if request.user.profile.avatar %}{{ request.user.profile.avatar.url }}
                    {% else %} 'static/img/default_profile.jpg {% endif %}" width="120" alt="photo">
                <div class="row">
                    <div class="col col-12 p-1  d-flex justify-content-center">
                        <b class="mx-2">{{ user.get_full_name}}</b>
                    </div>
                    <div class="col col-12 p-1 fs-5 fw-bold
                     {% if user.profile.status == 'ext'%} text-danger
                     {% elif user.profile.status == 'adv' %} text-success
                     {% else %} text-primary
                     {% endif %} d-flex justify-content-center">
                        {{ user.profile.get_status_display }}
                    </div>
                    <div class="col col-12 p-1  d-flex justify-content-center">
                        <b>{{ user.profile.balance }} {% trans '$' %}</b>
                    </div>
                </div>
            </div>
            <div class="col col-12 d-flex p-3  justify-content-center align-items-center">
                <div class="input-group">
                    <input id="recharge_balance" class="form-control" name="balance" placeholder="Введите сумму" >
                </div>
            </div>
            <div class="col col-12 d-flex p-3  justify-content-end align-items-center">
                <button for="recharge_balance" class="btn btn-warning w-100 p-2" type="submit">{% trans 'Recharge balance' %}</button>

            </div>
        </div>
    </form>
</div>


{% endblock %}

djmarketplace/app_users/templates/accounts/register.html
{% extends "templates/base.html" %}
{% load i18n %}
{% block title %} {% trans 'Sign-In' %} {% endblock %}

{% block content %}

<form method="post" action="" enctype="multipart/form-data">
    <h2 class="d-flex m-1 p-1  fw-bold text-light justify-content-end">{% trans 'Sign-In' %}</h2>
    <div class="form-signup w-100">
        <div class="row d-flex justify-content-center">
            <div class="col-6 rounded bg-light p-2 m-2">
                <h2 class="d-flex m-1 p-1  fw-bold  justify-content-end">{% trans 'Sign-In' %}</h2>
                <div class="{% if form.errors %}bg-danger p-2 m-2 rounded-2 text-light{% endif  %}">{{ form.errors }}</div>
                <ul class="my-3">

                    <input type="text" class="form-control my-2" name="username"
                           placeholder="{% trans 'username' %}" aria-label="username">
                    <input type="password" class="form-control my-2" name="password1"
                           placeholder="{% trans 'password' %}" aria-label="password1">
                    <input type="password" class="form-control my-2" name="password2"
                           placeholder="{% trans 'confirm password' %}"
                           aria-label="password2">
                    <input type="text" class="form-control my-2" name="first_name"
                           placeholder=" {% trans 'First name' %}" aria-label="first_name">
                    <input type="text" class="form-control my-2" name="last_name"
                           placeholder="{% trans 'Last name' %}" aria-label="last_name">
                    <input type="file" class="form-control my-2" placeholder="{% trans 'photo' %}"
                           name="avatar" aria-label="avatar">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-lg btn-primary ">{% trans 'Sign-In' %}</button>
                </ul>
            </div>
        </div>
    </div>
</form>
{% endblock %}